server:
  port: 8091

spring:
  application:
    name: order-service
  datasource:
    url: ${GL_DB_URL}
    username: ${GL_DB_USERNAME}
    password: ${GL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: order-service
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
rabbitmq:
    host: image-rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html 

services:
  order-service:
    base-url: http://order-service:8091
    timeout: 5000

INTERNAL_API_KEY: ${INTERNAL_API_KEY} 