spring.application.name=payment-service

server.port=8092

spring.datasource.url=${GL_DB_URL}
spring.datasource.username=${GL_DB_USERNAME}
spring.datasource.password=${GL_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}

spring.rabbitmq.host=image-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-attempts=3

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=payment-service

logging.level.root=INFO
logging.level.com.payment.payment_service=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

server.error.include-message=always
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false 

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

services.order.base-url=http://order-service
services.order.timeout=5000

INTERNAL_API_KEY=${INTERNAL_API_KEY:default-internal-key}