server:
  port: 8092

spring:
  application:
    name: payment-service
  datasource:
    url: ${GL_DB_URL}
    username: ${GL_DB_USERNAME}
    password: ${GL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: image-rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: payment-service
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info

INTERNAL_API_KEY: ${INTERNAL_API_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    default-url: /v3/api-docs/payment
    urls:
      - name: Payment
        url: /v3/api-docs/payment