server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
          include-expression: true
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20
            redis-rate-limiter.burstCapacity: 40
            redis-rate-limiter.requestedTokens: 1
            key-resolver: '#{@ipKeyResolver}'
      httpserver:
        access-log:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

jwt:
  secret: 

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
    org.springframework.web: INFO
    com.microservice_ecommerce.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: gateway
  api-docs:
    enabled: true
    path: /v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      userCircuitBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      productCircuitBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50