server:
  port: ${SERVER_PORT}

spring:
  application:
    name: catalog-service
  datasource:
    url: ${GL_DB_URL}
    username: ${GL_DB_USERNAME}
    password: ${GL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: image-rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

  data:
    elasticsearch:
      repositories:
        enabled: true

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  port: ${ELASTICSEARCH_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    preferIpAddress: true
    hostname: catalog-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET}

INTERNAL_API_KEY: ${INTERNAL_API_KEY}

integration:
  order:
    base-url: http://order-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    default-url: /v3/api-docs/catalog
    urls:
      - name: Catalog
        url: /v3/api-docs/catalog 